name: Enforce Dev and Hotfix Only PRs to Main

on:
  pull_request:
    branches:
      - main # Trigger only on PRs targeting main

jobs:
  check-source-branch-for-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch the full history for all branches
          
      - name: Check if PR source branch is dev or hotfix/*
        env:
          CURRENT_BRANCH: ${{ github.head_ref }} # Source branch of the PR
          PARENT_BRANCH: main
        run: |
          git fetch --all
          git checkout $CURRENT_BRANCH
          COMMON_ANCESTOR=$(git merge-base "$CURRENT_BRANCH" "main")
          echo "$COMMON_ANCESTOR"

          # if git branch --contains "$COMMON_ANCESTOR" | grep -q "$CURRENT_BRANCH"; then
          #   echo "$CURRENT_BRANCH is a child of $PARENT_BRANCH"
          # else
          #   echo "$CURRENT_BRANCH is not a child of $PARENT_BRANCH"
          # fi
          
          # # Check if we are merging into 'main' and if the current branch is valid
          # if [[ "$PARENT_BRANCH" == "main" ]] && [[ ! "$CURRENT_BRANCH" =~ ^hotfix/.* ]] && [[ "$CURRENT_BRANCH" != "dev" ]]; then
          #   echo "Error: Only PRs from 'dev' or 'hotfix/*' branches are allowed to merge into 'main'."
          #   exit 1
          # fi
