name: Enforce Dev and Hotfix Only PRs to Main

on:
  pull_request:
    branches:
      - main  # Trigger only on PRs targeting main

jobs:
  check-source-branch-for-main:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR source branch is dev or hotfix/*
        env:
          CURRENT_BRANCH: ${{ github.head_ref }}  # Source branch of the PR
        run: |
          # Set the parent branch by finding the closest common ancestor branch
          PARENT_BRANCH=$(git show-branch | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//')

          echo "Detected PARENT_BRANCH as $PARENT_BRANCH for branch $CURRENT_BRANCH"
          if [[ "$PARENT_BRANCH" == "dev" ]] && [[ ! "$CURRENT_BRANCH" =~ ^(feature|task|issue|fix)/.*$ ]]; then
            echo "Error: Only PRs from 'dev' or 'hotfix/*' branches are allowed to merge into 'main'."
            exit 1
          fi
