name: Auto Rebase Dev onto Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  # push:
  #   branches:
  #     - main

jobs:
  rebase-dev:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full history is fetched for rebasing

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Rebase dev onto main
        run: |
          git checkout dev
          git rebase main

      - name: Push rebased dev branch
        run: |
          git push origin dev --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
