name: Enforce Dev and Hotfix Only PRs to Main

on:
  pull_request:
    branches:
      - main # Trigger only on PRs targeting main

jobs:
  check-source-branch-for-main:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR source branch is dev or hotfix/*
        env:
          CURRENT_BRANCH: ${{ github.head_ref }} # Source branch of the PR
        run: |
          # Check if we are merging into 'main' and if the current branch is valid
          if [[ ! "$CURRENT_BRANCH" =~ ^hotfix/.* ]] && [[ "$CURRENT_BRANCH" != "dev" ]]; then
            echo "Error: Only PRs from 'dev' or 'hotfix/*' branches are allowed to merge into 'main'."
            exit 1
          fi
