name: Check source branch for PRs into dev

on:
  pull_request:
    branches:
      - dev

jobs:
  check-source-branch-for-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR source branch into dev is right
        env:
          CURRENT_BRANCH: ${{ github.head_ref }} # Source branch of the PR
        run: |
          if [[ "$PARENT_BRANCH" == "dev" ]] && [[ ! "$CURRENT_BRANCH" =~ ^(feature|task|fix)/.*$ ]]; then
            echo "Error: Only PRs from 'feature/**' or 'task/**' or 'issue/**' or 'fix/**' branches are allowed to merge into 'dev'."
            # exit 1
          fi
