name: Enforce Branch Naming Convention

on:
  create:
    branches:
      - main  # Trigger only when a branch is created based on `main`

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Enforce naming convention
        env:
          BRANCH_NAME: ${{ github.ref_name }}  # The name of the created branch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Check if the branch name matches the required pattern
          if [[ ! "$BRANCH_NAME" =~ ^hotfix/ ]] && [[ "$BRANCH_NAME" != "dev" ]]; then
            echo "Branch '$BRANCH_NAME' does not follow the naming convention ('hotfix/**' or 'dev'). Deleting it."
            # Delete the branch if it does not match 'hotfix/**' or 'dev'
            git push origin --delete "$BRANCH_NAME"
            exit 0  # Use exit 0 to mark the job as successful after deletion
          fi
