name: Auto Rebase Dev onto Main

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  # push:
  #   branches:
  #     - main

jobs:
  rebase-dev:
    if: github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          # required
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full history is fetched for rebasing
          token: ${{ steps.app-token.outputs.token }}
      - name: Fetch all branches
        run: git fetch --all

      - run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>'

      - name: Rebase dev onto main
        run: |
          git checkout dev
          git rebase main

      - name: Push rebased dev branch
        run: |
          git push origin dev --force-with-lease
